INSERT INTO [WHD].[dbo].[PROBLEM_TYPE] 
(ATTACHMENTS_ENABLED,DELETED,DESCRIPTION_REQUIRED,HIDE_SUBJECT,LEAD_TECH_ID,LOCKED,MODEL_REQUIRED,PARENT_ID,PRIORITY_TYPE_ID,PROBLEM_TYPE_ID,PROBLEM_TYPE_NAME,SHOW_CLIENT,SPECIFIC_CUSTOM_FIELDS,SPECIFIC_LOCATIONS,SUBSCRIBER_ID)
VALUES (1,0,0,1,1,0,1,15,3,39,'NAME OF CATEGORY',0,2,0,1);
